[package]
name = "rootspace-rs"
description = "A game wrapped in uncertainty and mis(t)ery"
version = "0.1.0"
authors = ["Eleanore Young"]

[dependencies]
failure = "^0.1.1"
failure_derive = "^0.1.1"
bitflags = "^1.0.1"
clap = "^2.28.0"
log = "^0.3.8"
fern = "^0.4.3"
glium = "^0.18.1"
